# Generated by Django 5.2 on 2025-05-02 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersalarywaitedpay',
            name='didnt_payed_days',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
