# Generated by Django 5.2 on 2025-05-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
