# Generated by Django 5.2 on 2025-05-01 17:41

import user_auth.models.Hw_model.model_home_work_lesson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='student_file',
            field=models.FileField(blank=True, null=True, upload_to='StudentHomework/'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/', validators=[user_auth.models.Hw_model.model_home_work_lesson.validate_file_size]),
        ),
    ]
