# Generated by Django 5.2 on 2025-05-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_mentor_user_remove_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_auth.staff'),
        ),
    ]
