# Generated by Django 5.2 on 2025-05-01 18:02

import django.db.models.deletion
import user_auth.models.Hw_model.model_home_work_lesson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_studenthomework_student_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouphomework',
            name='created',
        ),
        migrations.RemoveField(
            model_name='studenthomework',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='studenthomework',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='studenthomework',
            name='student_file',
        ),
        migrations.AlterField(
            model_name='grouphomework',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_homeworks', to='user_auth.group'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='group_homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homeworks', to='user_auth.grouphomework'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homeworks', to='user_auth.student'),
        ),
        migrations.CreateModel(
            name='StudentAddHw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='homeworks/additional/', validators=[user_auth.models.Hw_model.model_home_work_lesson.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='user_auth.studenthomework')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
