# Generated by Django 5.2 on 2025-05-02 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_workersalarywaitedpay_didnt_payed_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersalarypayed',
            name='datePayDay',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
