# Generated by Django 5.2 on 2025-05-02 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_teacher_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_auth.staff'),
        ),
    ]
