# Generated by Django 5.2 on 2025-05-02 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_workersalarypayed_datepayday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersalarypayed',
            name='datePayDay',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workersalarywaitedpay',
            name='didnt_payed_days',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
