# Generated by Django 5.2 on 2025-05-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary_pay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.workersalarypayed'),
        ),
    ]
