# Generated by Django 5.2 on 2025-05-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_emailotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailOTP',
            new_name='OTPCode',
        ),
    ]
