# Generated by Django 5.2 on 2025-05-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_rename_emailotp_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
