# Generated by Django 5.2 on 2025-05-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseduration',
            name='total_duration',
        ),
    ]
