# Generated by Django 5.2 on 2025-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_remove_courseduration_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseduration',
            name='total_duration',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
