from user_auth.models.base_user_model.user import *
from user_auth.models.student_package.model_attandace import *
from user_auth.models.student_package.model_student import *
from user_auth.models.student_package.model_courses import *
from user_auth.models.student_package.model_group import *
from user_auth.models.Hw_model.model_lesson import *
from user_auth.models.Hw_model.model_home_work_lesson import *
from user_auth.models.workers_models.model_teacher import *
from user_auth.models.workers_models.model_worker import *
from user_auth.models.workers_models.model_teacher import *
from user_auth.models.pay_model_salary.pay_model_for_worker import *
from user_auth.models.pay_model_salary.pay_model_for_student import *