from user_auth.permissions.base_user_permission.base_permission import *
from user_auth.permissions.hw_model_permission.group_hw_permission import *
from user_auth.permissions.hw_model_permission.student_hw_permission import *
from user_auth.permissions.lesson_permission.lesson_permission import *
from user_auth.permissions.lesson_permission.room_permission import *
from user_auth.permissions.pay_model_permission.student_pay_model_permission import *
from user_auth.permissions.pay_model_permission.payed_for_worker_permission import *
from user_auth.permissions.special_permissions.special_permissions import *

from user_auth.permissions.student_package_permission.student_permission import *
from user_auth.permissions.student_package_permission.student_add_hw_permission import *
from user_auth.permissions.student_package_permission.study_day_permission import *
from user_auth.permissions.student_package_permission.parents_permission import *
from user_auth.permissions.student_package_permission.group_permission import *
from user_auth.permissions.student_package_permission.course_duration_permission import *
from user_auth.permissions.student_package_permission.course_permission import *
from user_auth.permissions.student_package_permission.course_level_permission import *
from user_auth.permissions.student_package_permission.attandance_permission import *

from user_auth.permissions.workers_models_permission.worker_attendance_permission import *
from user_auth.permissions.workers_models_permission.mentor_permission import *
from user_auth.permissions.workers_models_permission.stafff_permission import *
from user_auth.permissions.workers_models_permission.teacher_permission import *
from user_auth.permissions.workers_models_permission.department_permission import *
from user_auth.permissions.workers_models_permission.worker_salary_payed_permission import *
from user_auth.permissions.workers_models_permission.position_level_permission import *
from user_auth.permissions.workers_models_permission.work_day_permission import *
from user_auth.permissions.workers_models_permission.WorkerSalaryWaitedPayPermission import *

